[features]
seeds = false
skip-lint = false

[programs.localnet]
last_rally = "AKPb5mB3Yn94QHUQrsQTSjDYUAgKqxPhZSUvUbkXgtaq"

[programs.devnet]
last_rally = "AKPb5mB3Yn94QHUQrsQTSjDYUAgKqxPhZSUvUbkXgtaq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/**/*.ts"
